### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by needhamwoodj**
Updating the links in the ReadMe file.

### CODE REVIEW

**Review by ZevEisenberg — APPROVED** [review]
It looks like this is also improved in iOS 13, so it may not be necessary any more on apps that are targeting that version. Might be worth testing and adding a note at the top of the blog post.

**Comment by mattwhitlock** [comment]
> It looks like this is also improved in iOS 13, so it may not be necessary any more on apps that are targeting that version. Might be worth testing and adding a note at the top of the blog post.

Good point, we'll probably add a note at the top. I hesitate to make too many changes as it feels like altering history which isn't the intent. But we should highlight that the underlying need has changed a bit. Thanks

**Review by mattwhitlock — CHANGES_REQUESTED** [review]
I'd adjust this slightly for a minor grammar quibble.
`post on the [Rightpoint's RPLabs site]`... to be
`post on [Rightpoint's RPLabs site]`...

**Review by mattwhitlock — APPROVED** [review]
Will update blog post separately.

**Pull request merged**
